#-----------------------------------------------------------------------------------------------------------------------
#Data
configuration:
  autor:
    email: flemantico@gmail.com
    nombre: Mariano Valle
  text: Global configuration DEV
#-----------------------------------------------------------------------------------------------------------------------
#Bacis' configuration of microservice:
spring:
  main:
    banner-mode: 'off'
  profiles:
    active: ${SERVER_CONFIGURATION_CONFIGURATION_ENVIRONMENT}
#-----------------------------------------------------------------------------------------------------------------------
#RabbitMQ configuration:
#  zipkin:
#En caso de levantar una instancia en un contenedor docker usar esta configuracion
#Para que tome la configuracion se deben reiniciar los contenedores docker
#    base-url: http://server-zipkin:9411/
#    sender:
#Para usar rabbit, tambien se debe agregar la dependencia
#      type: rabbit
#  rabbitmq:
#    host: microservicios-rabbitmq38
#-----------------------------------------------------------------------------------------------------------------------
#Loggin configuration:
logging:
  config: server-configuration/src/main/resources/logback.xml
  #config=classpath:/logback-spring.xml
#-----------------------------------------------------------------------------------------------------------------------
#Ribbon configuration
#Se puede habilitar si tenemos muchos microservicios y pocos recursos. Se pueden multiplicar los valores x 3
#ribbon:
#  ReadTimeout: '10000'
#  ConnectTimeout: '3000'
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: '20000'
#-----------------------------------------------------------------------------------------------------------------------
#Application config
microservices:
  message:
    log: ${APPLICATION_MESSAGE_LOG}
#-----------------------------------------------------------------------------------------------------------------------