#-----------------------------------------------------------------------------------------------------------------------
#Data
configuration:
  autor:
    email: flemantico@gmail.com
    nombre: Mariano Valle
  text: Global configuration DEV
#-----------------------------------------------------------------------------------------------------------------------
#Path configuration
server:
  servlet:
    context-path: /project
#-----------------------------------------------------------------------------------------------------------------------
#Bacis' configuration of microservice:
spring:
  main:
    banner-mode: 'off'
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: ${SERVER_CONFIGURATION_CONFIGURATION_ENVIRONMENT}
#-----------------------------------------------------------------------------------------------------------------------
#RabbitMQ configuration:
#  zipkin:
#En caso de levantar una instancia en un contenedor docker usar esta configuración
#Para que tome la configuración se deben reiniciar los contenedores docker
#    base-url: http://server-zipkin:9411/
#    sender:
#Para usar rabbit, también se debe agregar la dependencia
#      type: rabbit
#  rabbitmq:
#    host: microservicios-rabbitmq38
#-----------------------------------------------------------------------------------------------------------------------
#Loggin configuration:
logging:
  config: server-configuration/src/main/resources/logback.xml
  #config=classpath:/logback-spring.xml
#-----------------------------------------------------------------------------------------------------------------------
#Application config
microservices:
  message:
    log: ${APPLICATION_MESSAGE_LOG}
#-----------------------------------------------------------------------------------------------------------------------

#-----------------------------------------------------------------------------------------------------------------------
#Para solucionar los problemas con los nombres de hot
eureka:
  instance:
    prefer-ip-address: 'true'
#-----------------------------------------------------------------------------------------------------------------------