#-----------------------------------------------------------------------------------------------------------------------
#Data
configuration:
  text: service-item DEV
#-----------------------------------------------------------------------------------------------------------------------
#Bacis' configuration of microservice:
spring:
  application:
    name: service-item
  #-----------------------------------------------------------------------------------------------------------------------
  #Zipkin configuration:
  sleuth:
    sampler:
      probability: '1.0'
  zipkin:
    base-url: http://localhost:9411/
#-----------------------------------------------------------------------------------------------------------------------
#Port configuration:
#A dynamic port is defined to allow multiple instances.
server:
  port: ${PORT:${SERVER_PORT:0}}
#-----------------------------------------------------------------------------------------------------------------------
#Register in Eureka:
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    ##Esto es para manejar estáticamente el host. Se pasa a dinámico.
    #hostname: localhost
  client:
    register-with-eureka: 'true'
    fetch-registry: 'true'
#-----------------------------------------------------------------------------------------------------------------------
#Application configuration

#-----------------------------------------------------------------------------------------------------------------------