#-----------------------------------------------------------------------------------------------------------------------
#Data
configuration:
  text: server-configuration DEV
#-----------------------------------------------------------------------------------------------------------------------
